<?php
echo $openingPage;
echo $header;

?>
<main id="error404">
<section class="container">
    <h1>Erreur 404, la page demandé n'existe pas</h1>
    <video controls autoplay="autoplay">

        <source src="<?php echo IMAGE_URL;?>404.mp4"
                type="video/mp4">

        Désolé, votre navigateur n'est pas capable de lire notre super vidéo ! Dommage, elle est super !
    </video>
</section>


</main>