<?php
?>
<main id="error404">
    <section class="container">
        <h1>Erreur 404, la page demandé n'existe pas</h1>
        <p>Mais tu peux te distraire avec cette vidéo... ;)</p>
        <video controls autoplay="autoplay">
            <source src="<?php echo IMAGE_URL;?>404.mp4" type="video/mp4">
            Désolé, ton navigateur obsolète n'est pas capable de lire notre super vidéo ! Dommage, elle est vraiment super !
        </video>
    </section>
</main>