<?php
?>

<main id="account">

    <section id="info">
        <h2>Mes informations</h2>
        <article>
            <form action="updateAccount" method="post" class="flex flex-wrap flex-evenly">
                <div class="flex flex-column ">
                    <p>Identifiant et contact</p>
                    <label FOR="login">Login</label>
                    <input type="text" id="login" name="login" value="<?php echo $member->getLogin();?>">

                    <label FOR="mailAdress">Mail</label>
                    <input type="text"   id="mailAdress" name="mailAdress" value="<?php echo $member->getMailAdress();?>">
                </div>

                <div class="flex flex-column">
                    <p class="error"><?php echo $error; ?></p>
                    <p>Changer de mot de passe :</p>
                    <label FOR="password">Actuel</label>
                    <input type="password" id="password" name="password" placeholder="Mot de passe actuel">

                    <label FOR="passwordNew">Nouveau</label>
                    <input type="password" id="passwordNew" name="passwordNew" placeholder="Nouveau Mot de passe">
                    <label FOR="passwordNewVerif">Nouveau</label>
                    <input type="password" id="passwordNewVerif" name="passwordNewVerif" placeholder="Vérification">
                </div>

                <div class="flex-basis marge-top">
                <input type="submit"  value="Mettre à jour" class="button">
                </div>

            </form>

        </article>

    </section>
    <section id="myScores">
        <h2>Mes scores</h2>
        <?php foreach ($myScores as $score):
            if($score->getDifficulty() == 1): ?>

            <article class="<?php echo $score->getDifficultyClass(); ?>">
                <ul class="flex flex-evenly">
                    <li><?php echo $score->getScore(); ?></li>
                    <li><?php echo $score->getNbPoints();?>X<?php echo $score->getNbPoints();?></li>
                    <li><?php echo str_replace(' ', '<br>', $score->getTimestamp());?></li>

                </ul>



        </article>
        <?php endif;
            endforeach; ?>

        <?php foreach ($myScores as $score):

            if($score->getDifficulty() == 2): ?>

                <article class="<?php echo $score->getDifficultyClass(); ?>">
                    <ul class="flex flex-evenly">
                        <li><?php echo $score->getScore(); ?></li>
                        <li><?php echo $score->getNbPoints();?>X<?php echo $score->getNbPoints();?></li>
                        <li><?php echo str_replace(' ', '<br>', $score->getTimestamp());?></li>
                    </ul>



                </article>
            <?php endif;
        endforeach; ?>

        <?php foreach ($myScores as $score):

            if($score->getDifficulty() == 3): ?>

                <article class="<?php echo $score->getDifficultyClass(); ?>">
                    <ul class="flex flex-evenly">
                        <li><?php echo $score->getScore(); ?></li>
                        <li><?php echo $score->getNbPoints();?>X<?php echo $score->getNbPoints();?></li>
                        <li><?php echo str_replace(' ', '<br>', $score->getTimestamp());?></li>
                    </ul>



                </article>
            <?php endif;
        endforeach; ?>


    </section>

</main>
