<?php
?>

<main id="duelEnd">
    <section>
        <article class="<?php echo $score->getDifficultyClass(); ?> center">
            <ul class="flex flex-evenly">
                <li>
                    <?php echo $score->getLogin()?>
                </li>

                <li>
                    <?php echo $score->getLogin2()?>
                </li>
                <li>
                    <?php echo $score->getNbPoints().'X'.$score->getNbPoints(); ?>
                </li>
                <li>
                    <?php echo $score->getDateProvocation()?>
                </li>

            </ul>
            <ul class="flex flex-evenly">
                <li>
                    <?php echo $score->getScore(); ?>
                </li>

                <li>
                    <?php echo $score->getScore2(); ?>
                </li>
                <li>
                    <?php echo $score->getDifficultyClass();?>
                </li>
                <li>
                    <?php echo $score->getDateBack();?>
                </li>
            </ul>
        </article>
        <a href="duel" class="button">Un autre duel ?</a>
    </section>
</main>
