<?php
?>

<main id="selectDuel">
    <h1>Match en duel</h1>

    <section id="waitingDuel">
        <h2>Vos duels en attente</h2>
        <?php foreach ($duelScores as $duel): ?>
        <a href="game?duel=<?php echo $duel->getId(); ?>">
            <article class="<?php echo $duel->getDifficultyClass(); ?>">
                <ul class="flex flex-evenly">
                    <li>
                        <?php echo $duel->getLogin()?>
                    </li>
                    <li>
                        <?php echo $duel->getScore(); ?>
                    </li>
                    <li>
                        <?php echo $duel->getNbPoints().'X'.$duel->getNbPoints(); ?>
                    </li>
                    <li>
                        <?php echo $duel->getDateProvocation();?>
                    </li>
                </ul>
            </article>
        </a>
        <?php endforeach;?>
    </section>
    <section id="setDuel">
        <h2>Provoquer en duel</h2>
        <?php foreach ($members as $user): ?>
        <a href="game?id=<?php echo $user->getID();?>">
        <article>
            <div>
                <p><?php echo $user->getLogin();?></p>
                <p>Scores du joueur:</p>
            </div>

            <ul class="flex flex-evenly" >
                <?php foreach ($scoreManager->allMyBestsScores($user->getId()) as $score) : ?>
                <li class="<?php echo $score->getDifficultyClass(); ?>">
                    <p><?php echo $score->getNbPoints(); ?>X<?php echo $score->getNbPoints(); ?></p>
                    <p><?php echo $score->getScore();?></p>
                </li>
                <?php endforeach; ?>
            </ul>
        </article>
        </a>
        <?php endforeach;?>
    </section>
</main>
