<!--FOOTER-->
<footer id="footer" class="flex flex-evenly">
    <small>
        le projet bluePoint a été créé dans le cadre du projet final de la <a href="https://3wa.fr"><img alt="logo 3W Academy" src="<?php echo IMAGE_URL;?>logo3wa.png" /></a> par <a href="https://cheezpa.com">Kévin DUSAPIN</a>
    </small>
    <small><a href="mentions">Mentions Légales</a> </small>
</footer>
<script src="<?php echo JS_URL;?>footer/footer.js"></script>
</body>
</html>