<main>

    <h1>blue Point</h1>
    <div id="duel" <?php echo $showDuel; ?>> <?php echo $duelLogin; ?></div>
    <p>le but du jeu est simple: Cliquez sur le plus grand nombre de point bleu <span class="bluePoint"></span> dans le temps impartie</p>
    <section id="reglages">
        <article>
            <div>
                <label FOr="nbCase">Selectionnez le nombre de case voulu</label>
                <select <?php echo $disable; ?>  id="nbCase" name="nbCase">
                    <option value="3" <?php echo $nbpointsSelected3; ?>>3X3</option>
                    <option value="6" <?php echo $nbpointsSelected6; ?>>6X6</option>
                    <option value="9" <?php echo $nbpointsSelected9; ?>>9X9</option>
                </select>

                <label FOR="niveau">Difficulté</label>
                <select <?php echo $disable; ?> id="niveau" name="niveau">
                    <option value="1" <?php echo $difficultySelected1; ?>>Facile</option>
                    <option value="2" <?php echo $difficultySelected2; ?>>Moyen</option>
                    <option value="3" <?php echo $difficultySelected3; ?>>Difficile</option>
                </select>
                <div class="button" id="start">demarrer</div>
            </div>

            <div id="scoresFinal" class="flex scores hidden">
                <div id="yourScore1" class="marge">
                    <p>Score</p>
                    <p><span>0</span></p>
                </div>

                <div id="bestScore1" class="marge">
                    <p>Meilleur score </p>
                    <p><span><?php echo $myBestScore; ?></span></p>
                </div>
            </div>

        </article>
    </section>
    <section id="gameArea" class="hidden">
        <div id="startIn" class="hidden" ><p></p></div>
        <article id="theGame" class="border flex flex-column justify-normal hidden" >
            <div class="flex scores">
                <div id="yourScore2" class="marge">
                    <p>Score</p>
                    <p><span>0</span></p>
                </div>

                <div id="time" class="marge">
                    <p>temps restant</p>
                    <p><span>0</span></p>
                </div>

                <div id="bestScore2" class="marge">
                    <p>Meilleur score </p>
                    <p><span><?php echo $myBestScore; ?></span></p>
                </div>
            </div>
            <div id="pointView"></div>
        </article>

    </section>
    <div id="debug"></div>
</main>
<script src="js/game/class/Game.js"></script>
<script src="js/game/time.js"></script>
<script src="js/game/class/Point.js"></script>
<script src="js/game/submit.js"></script>
<script src="js/game/functions.js"></script>
<script src="js/game/main.js"></script>
