<!DOCTYPE html>
<html lang="fr">
<head>
    <title><?php echo $titrePage; ?></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--    FONTAWSOME-->
    <script src="https://kit.fontawesome.com/0006424b0a.js"></script>
    <!-- CSS Vendor -->
    <link rel="stylesheet" type="text/css" href="<?php echo CSS_URL; ?>/normalize.css" media="all" />
    <!-- CSS Perso -->
    <link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />

    <link rel="icon" href="<?php echo IMAGE_URL;?>favicon.ico">
</head>
<body>
<!--HEADER-->
<header>
    <a href="<?php echo $urlMonCompte; ?>" title="Mon compte"><div><p>Bonjour <?php echo $member->getLogin(); ?></p></div></a>
    <nav>
        <ul>
            <li>
                <a href="<?php echo HOST; ?>home" title="accueil"><i class="fas fa-home"></i></a>
            </li><!-- @whitespace
--><?php if($member->getIdentify()): ?><!-- @whitespace

        --><li class="duel">
                <a href="<?php echo HOST; ?>duel" title="Lancer un duel"><i class="fas fa-balance-scale-right"></i></a>
                <div class="<?php echo $notification; ?>"></div>
            </li>
            <li>
                <a href="<?php echo HOST; ?>unconnect" title="Deconnexion"><i class="fas fa-sign-out-alt"></i></a>
            </li><!-- @whitespace
--><?php else: ?><!-- @whitespace
        --><li>
                <a href="<?php echo HOST; ?>connexion" title="Connexion"><i class="fas fa-sign-in-alt"></i></a>
            </li><!-- @whitespace
        --><?php endif; ?><!-- @whitespace
        --><li>
                <a href="FAQ" title="FAQ"><i class="fas fa-question-circle"></i></a>
            </li>
        </ul>
    </nav>
</header>