<?php
?>
<main id="mentions">
    <section>
        <h2>Hebergeur</h2>
        <a href="https://www.ovh.com/fr/support/mentions-legales/">
            <article>OVH SAS est une filiale de la société OVH Groupe SAS, société immatriculée au RCS de Lille sous le numéro 537 407 926 sise 2, rue Kellermann, 59100 Roubaix.
            </article>
        </a>
    </section>

    <section>
        <h2>Auteur</h2>
        <article>
            <p>Le projet bluePoint est la propriété de Kévin DUSAPIN, créé par Kévin DUSAPIN pour son projet final de la 3W Academy <a href="https://3wa.fr"><img alt="logo 3W Academy" src="<?php echo IMAGE_URL;?>logo3wa.png" /></a></p>
        </article>
    </section>
    <section>
        <h2>Cookies</h2>
        <article>
            <p>Le site utilise les cookies pour fonctionner. Aucun cookie de traking n'est présent, ni aucun cookie tierce</p>
        </article>
    </section>
</main>
