<?php
?>
<main id="playerPage">
    <section id="compte" class="<?php echo $myPage; ?>">
        <a href="compte?id=<?php echo $member->getID();?>" class="button">
            <article>
            <p>Modifier mes infos</p>
            </article>
        </a>
    </section>

    <section id="duels">
        <h2>Les derniers duels de <?php echo $playerPage->getLogin();?> :</h2>
        <?php foreach ($duelListeAll as $duel): ?>

                <article class="<?php echo $duel->getDifficultyClass(); ?>">
                    <ul class="flex flex-evenly">
                        <li>
                            <a href="playerPage?id=<?php echo $duel->getIdPlayer(); ?>" title="page du joueur"><?php echo $duel->getLogin()?> <i class="fas fa-external-link-alt"></i></a>
                            <a href="playerPage?id=<?php echo $duel->getIdPlayer2(); ?>" title="page du joueur"><?php echo $duel->getLogin2()?> <i class="fas fa-external-link-alt"></i></a>
                        </li>

                        <li>
                            <?php echo $duel->getScore(); ?><br>
                            <?php echo $duel->getScore2(); ?>
                        </li>


                        <li>
                            <?php echo $duel->getNbPoints().'X'.$duel->getNbPoints(); ?>
                        </li>
                        <li>
                            <?php echo str_replace(' ', '<br>', $duel->getDateProvocation());?>
                        </li>
                    </ul>
                </article>

        <?php endforeach;?>
    </section>


    <section id="myScores">
        <h2>Les scores de <?php echo $playerPage->getLogin();?> :</h2>
        <?php foreach ($myScores as $score):
            if($score->getDifficulty() == 1): ?>

                <article class="<?php echo $score->getDifficultyClass(); ?>">
                    <ul class="flex flex-evenly">
                        <li><?php echo $score->getScore(); ?></li>
                        <li><?php echo $score->getNbPoints();?>X<?php echo $score->getNbPoints();?></li>
                        <li><?php echo str_replace(' ', '<br>', $score->getTimestamp());?></li>

                    </ul>



                </article>
            <?php endif;
        endforeach; ?>

        <?php foreach ($myScores as $score):

            if($score->getDifficulty() == 2): ?>

                <article class="<?php echo $score->getDifficultyClass(); ?>">
                    <ul class="flex flex-evenly">
                        <li><?php echo $score->getScore(); ?></li>
                        <li><?php echo $score->getNbPoints();?>X<?php echo $score->getNbPoints();?></li>
                        <li><?php echo str_replace(' ', '<br>', $score->getTimestamp());?></li>
                    </ul>



                </article>
            <?php endif;
        endforeach; ?>

        <?php foreach ($myScores as $score):

            if($score->getDifficulty() == 3): ?>

                <article class="<?php echo $score->getDifficultyClass(); ?>">
                    <ul class="flex flex-evenly">
                        <li><?php echo $score->getScore(); ?></li>
                        <li><?php echo $score->getNbPoints();?>X<?php echo $score->getNbPoints();?></li>
                        <li><?php echo str_replace(' ', '<br>', $score->getTimestamp());?></li>
                    </ul>



                </article>
            <?php endif;
        endforeach; ?>


    </section>
</main>
